Pipe read
Pelagicore/dbus-proxy pull request #14
Opened 2017-04-06 11:27 UTC by breakreturn

2017-04-06 11:34 UTC, rpannek approved these changes

2017-04-06 11:38 UTC, tobsan requested changes

2017-04-06 11:38 UTC, tobsan commented on README.md
> +contexts that trouble shooting and debugging. It's not suitable for production
troubleshooting is one word

2017-04-06 11:38 UTC, tobsan commented on README.md
> +is meant to be spawned bt another process that writes to stdin of `dbus-proxy`. When
spawned by*

2017-04-06 11:38 UTC, tobsan commented on src/proxy.c
> +#include <stdlib.h>
double include

2017-04-06 11:38 UTC, tobsan commented on src/proxy.c
> +    mainloop = g_main_loop_new(NULL, FALSE);
These magic values could deserve some comment.

2017-04-06 12:33 UTC, tobsan approved these changes
Just a comment, looks good to me.

2017-04-06 12:33 UTC, tobsan commented on src/proxy.c
> +    char buf[100] = {0};
This feels unnecessarily large.

2017-04-07 11:35 UTC, frznlogic approved these changes

2017-04-10 07:52 UTC, kursatkobya commented on src/proxy.c
> +    char *full_section = calloc(sizeof(char), 30);
better to use 
`calloc(30, sizeof(char));`
since the first argument indicates number of elements

2017-04-10 08:23 UTC, kursatkobya commented on src/proxy.c
> +
maybe getting rid of a new variable would be nicer. So instead `#ifdef LOG_TO_STDOUT` you can add 
```
#ifndef LOG_TO_STDOUT
    g_log_set_handler(NULL, G_LOG_LEVEL_MASK, log_handler_silent, NULL);
#endif
```

2017-04-10 08:24 UTC, kursatkobya commented on CMakeLists.txt
> +endif()
so is it possible to undeclare LOG_TO_FILE in this case

2017-04-10 08:28 UTC, kursatkobya approved these changes
Looks good, i have just minor comments.

2017-04-10 10:45 UTC, merged