tests: Adds tests for properties "leak"
Pelagicore/dbus-proxy pull request #18
Opened 2017-04-18 11:55 UTC by breakreturn

Test pinpoints the behavior where the proxy can't
disallow calls to e.g. GetAll based on the interface
argument, and thus possibly "leak" properties from
an otherwise disallowed interface.

Signed-off-by: Joakim Gross <joakim.gross@pelagicore.com>

2017-04-18 15:18 UTC, thenor commented on component-test/test_dbus_proxy.py
> +        # otherwise not allowed by be reached by the proxy.
I think there is a typo in this text. "... allowed **by** be reached ..." ?

2017-04-18 15:20 UTC, thenor commented on component-test/service_stubs.py
> +    context. E.g, dbus-proxy will not disallow properties on interface X
I think there is a typo here: "E.g**,** ..."

2017-04-18 15:23 UTC, thenor requested changes
Just found two small typos. Otherwise a-OK.

2017-04-19 07:00 UTC, frznlogic approved these changes

2017-04-19 07:01 UTC, frznlogic commented on component-test/service_stubs.py
> +                                        PROP_KEY_2 + iface: PROP_VALUE_2 + iface}
I understand the code, but IMHO, the old code is actually easier to read/understand for me ;).

2017-04-19 07:04 UTC, breakreturn commented on component-test/service_stubs.py
> +                                        PROP_KEY_2 + iface: PROP_VALUE_2 + iface}
Yes it was, but it also did something else. Would you propose to have the new functionality hard-coded?

2017-04-19 07:09 UTC, thenor approved these changes

2017-04-19 07:23 UTC, merged

2017-04-19 08:35 UTC, frznlogic commented on component-test/service_stubs.py
> +                                        PROP_KEY_2 + iface: PROP_VALUE_2 + iface}
Definitely not, it was mostly a comment on the discussion we had over the last few weeks on the topic of hardcoded variables etc ;). I digress.